### ISSUE TITLE
Add a ping to check whether activity stream is enabled

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/ping-centre#100]
We should add a simple health check ping whose code path lives entirely outside of the activity stream system addon, ie it lives in the core browser code and runs at startup.  It should check whether or not the activity stream system addon is enabled via its pref:

browser.newtabpage.activity-stream.enabled

and also collect basic things like:

browser version
browser channel
locale
geo
shield experiment ids/branches

This will help us debug issues around activity stream not initializing properly.

**Comment by dmose** [comment]
@jaredkerim timestamp of what?

**Comment by emtwo** [comment]
@dmose I assume it's timestamp of when the ping is sent which is populated server-side

**Comment by emtwo** [comment]
Landed in m-c: https://hg.mozilla.org/mozilla-central/rev/698b17a7805c
This needs to be uplifted to 57 so that we can catch any bugs there as we do shield studies
