### ISSUE TITLE
Activity Stream Performance Dashboard partially broken

### ISSUE THREAD

**Issue by dmose** [mozilla/ping-centre#101]
`[Nightly - Non-Preloaded Only] Percentiles of Perceived Time to First Topsites Paint` doesn't render at all with an error message.

Replacing `{{x_axis}}` with `date` in the SQL appears to fix it.

**Comment by emtwo** [comment]
Oops. forgot to undo some changes there that didnt work. Should be fixed now: https://sql.telemetry.mozilla.org/queries/36182#96862

**Comment by dmose** [comment]
Thanks, that looks better, though the line labels in the key are still regressed.

**Comment by emtwo** [comment]
oops. I'll fix that too
