### ISSUE TITLE
Add an onyx endpoint and disco/inferno ETL and redshift table for health pings

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/ping-centre#103]
We are adding a new health check ping in #100 and we need to do additional server side work to facilitate this.  Let's agree on a schema and then we can add the ingestion endpoints, etls, and redshift table.

**Comment by emtwo** [comment]
Here is my suggestion for fields in the ping:

Default Values set by Ping Centre:
version
release_channel
locale
shield_id
client_id
topic

Health Telemetry Specific Values:
event (e.g. "activity_stream_enabled")
value (e.g. "False")

Server Side Values:
country_code
date
receive_at
os
device
.....

**Comment by ncloudioj** [comment]
Do we want other types for the `value` column? For example, the pref could be boolean, integer, and string in Firefox. For simplicity, we can also treat them all as string, and do the conversion durgin the query time.

**Comment by emtwo** [comment]
Yes, sorry I didn't mean the `value` field should be boolean. It can be anything so string is a good idea.

**Comment by ncloudioj** [comment]
Closed via splice #402 and infernyx #107
