### ISSUE TITLE
Update Nightly dashboard to filter by channel

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/ping-centre#104]
The dashboard here:

https://sql.telemetry.mozilla.org/dashboard/activity-stream-system-addon-metrics-summary

checks for version == '57.0' but not channel, so as 57 rolls out to beta, the population is hugely increasing and it looks like some of our metrics are dropping.  Let's filter this just to the nightly population so we can get a clearer sense of continuity within a channel.

Perhaps we could add a similar dashboard for each channel.

**Comment by emtwo** [comment]
https://sql.telemetry.mozilla.org/dashboard/activity-stream-system-addon-metrics-summary

This dashboard has been updated. Note that it is now agnostic of version numbers and is only there to compare nightly vs beta channel engagement overall.

For the beta channel, this no longer includes any experiment data as we're on by default now.
