### ISSUE TITLE
Add geo collection from client

### ISSUE THREAD

**Issue by emtwo** [mozilla/ping-centre#117]
The onyx geo service does not match up with the client geo service which is used to make decisions such as pocket feed assignment.

This makes analysis inaccurate when trying to look at pocket-enabled users.

**Comment by tspurway** [comment]
@ncloudioj, @emtwo 

Nan, Marina - we'd really like to get this landed and an uplift to Beta started for this ticket.  Ideally, that would be this week!  We also need ticket #111 in the same uplift.  Marina is leaving for a conference on Friday, so Nan, could you help make sure the client side of this lands?

**Comment by ncloudioj** [comment]
Yep, I'll pick them up.

**Comment by ncloudioj** [comment]
This is closed via 4fcdb6ebd9a1480d120f433c0ba6a75fe070ae82
