### ISSUE TITLE
Add fields for better identify onboarding user type

### ISSUE THREAD

**Issue by gasolin** [mozilla/ping-centre#121]
Related to [Bug 1412164 - add new column for onboarding telemetry](https://bugzilla.mozilla.org/show_bug.cgi?id=1412164) (client side work), we also need add columns in server side.

for `firefox_onboarding_sessions_daily` table,
* add `tour_type` string column 
(valid string are `new`, `update`, default `update`)

for `firefox_onboarding_events_daily` table,
* add `timestamp` column, (save event trigger time, same format as session_begin)
* add `tour_type` string column
(valid string are `new`, `update`, default `update`)
* add `tour_source` string column
(valid string are `default`, `watermark`, default `default`, its the same exists in `firefox_onboarding_sessions_daily` table)
* add `bubble_state` string column (not send this data now, will append in following client update)
(valid string are `bubble`, `dot`, `hide`, default `bubble`)
* add `notification_state` string column (not send this data now, will append in following client update)
(valid string are `show`, `hide`, `finish`, default `show`)

And we will add `onboarding-icon-click` event in `firefox_onboarding_events_daily` table, but I think it does not require column change

**Comment by gasolin** [comment]
@ncloudioj  could you help on this?

**Comment by ncloudioj** [comment]
@gasolin Sure, will do.

Also, just a reminder that once we add those new columns to the database, the existing data records will not have values for them (i.e. the value will be `null`). It might need some extra care when querying the database.

**Comment by gasolin** [comment]
got it, thanks for notice

**Comment by gasolin** [comment]
related client code is landed into nightly https://bugzilla.mozilla.org/show_bug.cgi?id=1412164

**Comment by gasolin** [comment]
As discussion on slack, this database change might be delayed due to the database scale up, but should be able to catch up before 57 hits the road

**Comment by ncloudioj** [comment]
@gasolin This is now fixed.
