### ISSUE TITLE
Update Engagement query templates to divide by active_ticks

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/ping-centre#123]
To account for unmeasurable user unenrollment in studies, we need to move to computing all of our engagement metrics divided by active ticks until we have a better way to filter for unenrolled users.

**Comment by emtwo** [comment]
Average Events Per Active Hour Template (Non-mapped): https://sql.telemetry.mozilla.org/queries/48795
Average Events Per Active Hour Template (Mapped): https://sql.telemetry.mozilla.org/queries/48830

Non-mapped TTest templates:
New Users: https://sql.telemetry.mozilla.org/queries/48422
Existing Users: https://sql.telemetry.mozilla.org/queries/48428

Mapped TTest templates:
New Users: https://sql.telemetry.mozilla.org/queries/48426
Existing Users: https://sql.telemetry.mozilla.org/queries/48433
