### ISSUE TITLE
Audit redash auto-executed queries 

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/ping-centre#125]
The query latency in Redash is getting higher as those auto-executed queries are packed in the run queue. More importantly, the query performance gets affected by that considerably.

Let's audit all those queries to:

* remove the unused queries (AS for TP and other ping-centre queries)
* reschedule other queries so that they won't be hammering the database at the same time

**Comment by emtwo** [comment]
I've turned off the refresh on the following Test Pilot A-S dashboards:
https://sql.telemetry.mozilla.org/dashboard/activity-stream-executive-summary
https://sql.telemetry.mozilla.org/dashboard/activity-stream-distributions
https://sql.telemetry.mozilla.org/dashboard/hang-tight-analysis
https://sql.telemetry.mozilla.org/dashboard/activity-stream-interactions
https://sql.telemetry.mozilla.org/dashboard/activity-stream-make-activity-stream-great-again
https://sql.telemetry.mozilla.org/dashboard/activity-stream-metrics-summary
https://sql.telemetry.mozilla.org/dashboard/activity-stream-performance
https://sql.telemetry.mozilla.org/dashboard/activity-stream-user-preferences
https://sql.telemetry.mozilla.org/dashboard/activity-stream-shield-study-filtered-performance_1

I've audited the queries @jbuck shared with the following:
5442 - Old Shield Study (turned off)
5796 - Stefan’s iOS query
6118 - System Add-on Engagement - not referenced often - Changed from 12 hours to 7 days
6119 - System Add-on Engagement -not referenced often - Changed from 12 hours to 7 days
6120 - System Add-on Engagement -not referenced often - Changed from 12 hours to 7 days
9524 - Nightly System Add-on performance - changed from 6h to 24h
10830 - Nightly System Add-on performance - changed from 6h to 24h
11384 - System Add-on Engagement -not referenced often - Changed from 12 hours to 7 days
23643 - System Add-on Engagement -not referenced often - Changed from 12 hours to 7 days
34332 - One time analysis of event counts per user per day - turned off
36182 - Nightly System Add-on performance - changed from 12h to 24h
40351 - Nightly System Add-on performance - changed from 12h to 24h
40379 - Named query (seemed related to performance_ - turned off
48776 - Release channel mau/dau/wau - Changed from 12 hours to 24 hours
48831 - Release channel interaction rates - stays at 24h
48890 - Release channel interaction rates for pocket off - Changed from 12 hours to 24 hours
48922 - Release channel about:newtab interactions - stays at 24h
48960 - Stefan’s iOS query
5796 - Stefan’s iOS query

**Comment by ncloudioj** [comment]
@jbuck FYI ^

Thanks a ton! @emtwo
