### ISSUE TITLE
Add new table for tracking new onboarding telemetry

### ISSUE THREAD

**Issue by gasolin** [mozilla/ping-centre#127]
Related to [Bug 1413830 - Data schema change for onboarding telemetry](https://bugzilla.mozilla.org/show_bug.cgi?id=1413830) (client side work), we also need to add new table and columns on the server side.

Data Review state: **passed**

We will send `firefox_onboarding_session2` and `firefox_onboarding_event2` as new topics.

for `firefox_onboarding_sessions2_daily` table,
* addon_version: string,
* category: one of these string ["logo-interactions", "onboarding-interactions",
    "overlay-interactions", "notification-interactions"],
* page: one of these string ["about:newtab", "about:home"],
* parent_session_id: uuid (string),
* root_session_id: uuid (string),
* session_begin: timestamp, integer,
* session_end: timestamp, integer,
* session_id: uuid (string),
* tour_type: one of these string ["new", "update"],
* type: string,

for `firefox_onboarding_events2_daily` table,
* addon_version: string,
* bubble_state: one of these string ["bubble", "dot", "hide"]
* category: one of these string ["logo-interactions", "onboarding-interactions",
    "overlay-interactions", "notification-interactions"],
* current_tour_id: string
* logo_state: one of these string ["logo", "watermark"].
* notification_impression: integer
* notification_state: one of these string ["show", "hide", "finished"]
* page: one of these string ["about:newtab", "about:home"],
* parent_session_id: uuid (string),
* root_session_id: uuid (string),
* target_tour_id: string
* timestamp:  timestamp, integer,
* tour_type: one of these string ["new", "update"],
* type: string,
* width: integer

PingCentre module will append `locale`, `client_id` columns automatically, should I also doc that?

**Comment by gasolin** [comment]
@ncloudioj could you help on this?

**Comment by gasolin** [comment]
FYR here's the live schema for session pings
https://github.com/mozilla/gecko-dev/blob/master/browser/extensions/onboarding/OnboardingTelemetry.jsm#L90

and event pings
https://github.com/mozilla/gecko-dev/blob/master/browser/extensions/onboarding/OnboardingTelemetry.jsm#L106

**Comment by ncloudioj** [comment]
@gasolin I'm on it.

**Comment by ncloudioj** [comment]
> We will send firefox_onboarding_sessions2 and firefox_onboarding_events2 as new topics.

Just to be clear, looks like the topics are `firefox_onboarding_session2` and `firefox_onboarding_event2` from https://github.com/mozilla/gecko-dev/blob/master/browser/extensions/onboarding/OnboardingTelemetry.jsm#L125

@gasolin Can you confirm?

**Comment by gasolin** [comment]
yes, its `firefox-onboarding-event2`, sorry for the typo!

**Comment by ncloudioj** [comment]
Thanks for confirming this! @gasolin 

How can I enable this in onboarding? Using the latest Nightly, still seeing the telemetry in V1 schema though.

**Comment by gasolin** [comment]
we land the validator in central first, the v2 patch is in review now
You could apply PR locally https://reviewboard.mozilla.org/r/198384/

**Comment by ncloudioj** [comment]
Cool, the new schema (as described above) has been deployed in stage. Let me know once the patch lands in nightly.

**Comment by ncloudioj** [comment]
@gasolin The new tables have been created in prod.

**Comment by gasolin** [comment]
thanks!
