### ISSUE TITLE
New client: watchdog-proxy

### ISSUE THREAD

**Issue by ghost** [mozilla/ping-centre#130]
Hi,  The Test Pilot team is working on a new project that we'd like to use Ping Centre with.  I wrote a [metrics document](https://github.com/mozilla/watchdog-proxy/blob/master/docs/metrics.md) that breaks down the events we'd fire and the questions we want to answer.

I'd be happy to talk through the document and get advice on the ping structure and if there are better ways to answer the questions.  I'm filing this issue as a kick-off -- what other data do you need?  Should I schedule a meeting?  Thanks!

**Comment by ncloudioj** [comment]
That metrics document looks great, I believe we can proceed as follows:
* Assign a Ping-Centre topic to this experiment, such as "watchdog-proxy", all the pings generated by this experiment should include a field `"topic": "watchdog-proxy"`
* Let's turn all the ping types in the metrics document into actual schema (perhaps in JSON?), and attach them to this thread. We will prepare all the bits on our end.
* Implement the telemetry code for watchdog-proxy, if it has access to jsm modules, we have a Ping-Centre client in m-c. If not, it could just use anything that can issue HTTP POST, like fetch.
* We will do end-to-end test in stage to ensure everything works as expected
* Deploy to prod

**Comment by lmorchard** [comment]
> Implement the telemetry code for watchdog-proxy, if it has access to jsm modules, we have a Ping-Centre client in m-c. If not, it could just use anything that can issue HTTP POST, like fetch.

Yeah, for what it's worth, this is a fully server-side application using AWS Lambda. No code in Firefox.

**Comment by ncloudioj** [comment]
@lmorchard Thanks for clarifying it. Then just HTTP POST to Ping-Centre's endpoint directly:
* stage: https://onyx_tiles.stage.mozaws.net/v3/links/ping-centre
* prod: https://tiles.services.mozilla.com/v3/links/ping-centre

Those endpoints could be found at `browser.ping-centre.stage.endpoint` and `browser.ping-centre.production.endpoint` in about:config

**Comment by wresuolc** [comment]
Thanks for the comments.  I added a topic and examples to our documentation @ https://github.com/mozilla/watchdog-proxy/blob/master/docs/metrics.md

**Comment by ncloudioj** [comment]
Since Ping-Centre's database can handle null values quite efficently, looks like we can just use a single "wide" table for all those "events", 

```js
{
  // required fields
  "topic": "watchdog-proxy",
  "timestamp": "2018-05-18T16:38:33.464Z",
  "event": ["new_item" | "worker_awakes" | "worker_works" | "worker_sleeps"],

  // optional fields (i.e they are all nullable, each row in the table has all of them,
  // but only certain columns will be populated for each individual event)
  "consumer_id": 101,
  "watchdog_id": "9ad08ec4-be1a-4327-b4ef-282bed37621f"
  "type": "png",

  "items_in_queue": 1504,
  "items_to_claim": 250,

  "watchdog_id": "9ad08ec4-be1a-4327-b4ef-282bed37621f"
  "photodna_tracking_id": "1_photodna_a0e3d02b-1a0a-4b38-827f-764acd288c25",
  "is_match": false,
  "is_error": false

  "timing_retrieved": 8,
  "timing_sent": 89,
  "timing_received": 161,
  "timing_submitted": 35,

  "items_in_queue": 1504,
  "items_processed": 250
}
```

I'd also recommend to add a dummy column `date` to the table, the client doesn't need to include it in the payload, the ETL job can infer it from `timestamp`, for two reasons:
* make it easier to query the table on the daily basis (no need to parse the timestamp)
* we can use it to evenly distribute the data across the cluster so that the query can run faster.

What do you think? @wresuolc

**Comment by wresuolc** [comment]
Adding `date` sounds good.  

And a single wide table sounds good too.  I'm getting data review right now (https://github.com/mozilla/watchdog-proxy/issues/33) so maybe we should wait for that before implementing any schemas, but this is looking great!  Thanks.

**Comment by ncloudioj** [comment]
Sounds good, just let me know once it's good to go.

**Comment by clouserw** [comment]
We've got data review and legal approval.  We're good to move forward here

**Comment by ncloudioj** [comment]
@clouserw Sounds good. Could you point me to the final version of schema? I can set it up on our end.

**Comment by clouserw** [comment]
What you have above (with the fake `date` column) sounds great.  Thanks @ncloudioj

**Comment by ncloudioj** [comment]
Will let you know once it's ready in Ping-centre.

**Comment by ncloudioj** [comment]
Looks like there are some updates in watchdog-proxy's  [telemetry document](https://github.com/mozilla/watchdog-proxy/blob/master/docs/metrics.md#events). I've updated the proposed schema accordingly.

Can you confirm? @clouserw or @lmorchard 

```js
{
  // required fields
  "topic": "watchdog-proxy",
  "timestamp": "2018-05-18T16:38:33.464Z",
  "event": ["new_item" | "poller_heartbeat" | "worker_works"],

  // optional fields (i.e they are all nullable, each row in the table has all of them,
  // but only certain columns will be populated for each individual event)

  // common fields for new_item and worker_works  
  "consumer_name": "screenshots",
  "watchdog_id": "9ad08ec4-be1a-4327-b4ef-282bed37621f",

  // new_item specific fields
  "type": "png",

  // poller_heartbeat specific fields
  "poller_id": "31417de1-b3ef-4e90-be3c-e5116d459d1d",
  "items_in_queue": 1504,
  "items_in_progress": 22,
  "items_in_waiting": 38,

  // worker_works specific fields
  "photodna_tracking_id": "1_photodna_a0e3d02b-1a0a-4b38-827f-764acd288c25",
  "worker_id" "8cdb1e6b-7e15-489d-b171-e7a05781c5da",
  "is_match": false,
  "is_error": false,
  "timing_sent": 89,
  "timing_received": 161,
  "timing_submitted": 35,
}
```

**Comment by lmorchard** [comment]
>  "timestamp": "2018-05-18T16:38:33.464Z",

[Changing this to be Unix epoch time in microseconds](https://github.com/mozilla/watchdog-proxy/issues/147)

Other than that, the rest of the fields look good to me!

**Comment by clouserw** [comment]
Watchdog stage is now pointing at the stage URL above

**Comment by ncloudioj** [comment]
Ping-Centre is ready in stage as well. Let's verify all the metrics once watchdog gets inbound traffic.

**Comment by clouserw** [comment]
Bug to verify metrics is at https://github.com/mozilla/watchdog-proxy/issues/96
