### ISSUE TITLE
ping-centre is not inserting required commonSchema field 'event_type'

### ISSUE THREAD

**Issue by 6a68** [mozilla/ping-centre#25]
`commonSchema.js` defines three fields: `client_id`, `topic`, and `event_type`.

`client_id` and `topic` are [inserted](https://github.com/mozilla/ping-centre/blob/master/ping-centre.js#L36-L39) by `ping-centre.js`, but `event_type` is not.

Is this a bug or intentional?

**Comment by emtwo** [comment]
This was intentional. `event_type` is supposed to be up to the user of ping centre to specify when they generate their pings.

I'm going to close this issue. If you're interested in or expecting another type of behaviour please file another one with that. Thanks!
