### ISSUE TITLE
One vs. Multiple Events per Ping

### ISSUE THREAD

**Issue by emtwo** [mozilla/ping-centre#27]
I noticed that the new test pilot ping sends an array of events rather than 1 at a time. The common schema in this case does not make sense because it expects one event type per ping.

Let's have a second common schema that takes this into account and let's agree that the event type field will have a common name. Right now we've got `event_type` in the common schema vs. `event` in the test pilot schema

**Comment by emtwo** [comment]
@ncloudioj @6a68: I was unfortunately not around when you guys discussed this. In general, we want to have a shared field name for event types so that we can easily auto-generate graphs based on the event type.

Should we change `event` to `event_type` in the test pilot schema, or change `event_type` to `event`? Or no preference?

@ncloudioj: I'm assuming Onyx will be breaking up the array of events for test pilot then?

**Comment by ncloudioj** [comment]
Yes, the multiple events ping will be unwrapped by Infernyx.

@emtwo could you remind me that if is there any difference between `event` and `event_type`? I am assuming they're the same. In this case, Testpilot ping might have multiple events, that's why it doesn't use the one in the common schema, right?

**Comment by emtwo** [comment]
Yes. So `event` and `event_type` are essentially the same thing. Right now the `testpilot` schema doesn't quite make sense because it has its own array of `event`s but also extends the common schema which has `event_type`

This issue is to create a second common schema that allows for an array of `event`s

**Comment by ncloudioj** [comment]
Closing it as the new schema for Test Pilot is no longer nested.
