### ISSUE TITLE
Update publisher permissions

### ISSUE THREAD

**Issue by emtwo** [mozilla/ping-centre#31]

**Comment by ncloudioj** [comment]
I've already done this under my npm account as @6a68 needed it to do some tests/integration. Wonder if we can do this under some other account, e.g. mozilla or A-S, I can back out the temporary one.

**Comment by emtwo** [comment]
Ah, I missed that. Yes, agreed that publishing under Mozilla would be ideal. I'll relabel this issue to be for that.

**Comment by 6a68** [comment]
Unlike Github, there's not really any official Mozilla org on npm. Usually works out pretty well if someone publishes the library, then add a bunch of teammates as maintainers (this is pretty easy through the npm website UI).

**Comment by emtwo** [comment]
Ok I'm going to rename this issue to be about adding maintainers - We should at least have myself, @ncloudioj and @6a68 able to publish for now.

**Comment by 6a68** [comment]
@emtwo I've just published [mozilla-ping-centre](https://www.npmjs.com/package/mozilla-ping-centre) to npm, so I can get test pilot integrated while nanj is out of office. I've added you, nanj, and k88hudson as collaborators. You should be able to add other collaborators, either via the command line or the npm website. I'm good to delete this in favor of the shorter `ping-centre` package name when nanj gets back, or not, whatever you'd prefer.

**Comment by pdehaan** [comment]
Reminder that we have a [**ping-centre**](http://npm.im/ping-centre) and [**mozilla-ping-centre**](http://npm.im/mozilla-ping-centre) currently published to npm.
Not sure if we want to keep one over the other and delete/unpublish the other to avoid confusion.

But yeah, @6a68's https://github.com/mozilla/ping-centre/issues/31#issuecomment-278124220 above sums it up quite eloquently.

**Comment by ncloudioj** [comment]
Hey folks, I've added you all to the collaborators. My apologies for the inconvenience.
