### ISSUE TITLE
Better validation before importing user-specified schemas?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/ping-centre#45]
Ref: https://github.com/mozilla/ping-centre/pull/36#discussion_r99694219

Currently in the [`PingCentre()` constructor](https://github.com/mozilla/ping-centre/blob/master/ping-centre.js#L18-L19) we "blindly" try `require()`ing a user-specified `topic` schema from disk.
We _may_ want to do a bit more validation before loading files, in case user's try and pass funny path strings like "../../../../etc/host" or something (not that it'd work, but still).

**Comment by 6a68** [comment]
One solution might be to have an index.js inside the schemas folder, then explicitly load all supported schemas there, exported as an object:

```js
// schemas/index.js
'use strict';

module.exports = {
  'testpilot': require('./testpilot'),
  'common': require('./commonSchema')
};
```

Then, instead of this:
```js
// inside PingCentre constructor
const schema = require(`./schemas/${topic}`);
this._schema = schema || commonSchema;
```

could do something like:
```js
const schemas = require('./schemas')
this._schema = schemas[topic] || schemas['common']
```

**Comment by pdehaan** [comment]
:+1: Although not sure if we want to do a silent "common" fallback versus a more aggressive error of "Unknown schema ${topic}".
