### ISSUE TITLE
SDK fetch polyfill problem

### ISSUE THREAD

**Issue by 6a68** [mozilla/ping-centre#47]
When the Firefox SDK loads code, it's loaded into an environment in which there's no `window`, no `self`, and no `global`. This throws off pretty much every `fetch` polyfill detection approach, which means `ping-centre` doesn't load properly.

For instance, in `isomorphic-fetch`, the [browser-compatible version](https://github.com/matthew-andrews/isomorphic-fetch/blob/master/fetch-npm-browserify.js#L5) uses `whatwg-fetch`, which in turn [assumes](https://github.com/github/fetch/blob/master/fetch.js#L458) that the global object is available as either `self` or `this`. In the case of an SDK addon, it attaches its `fetch` to the wrong object, and the polyfill doesn't work.

So, this is one way to get `fetch` into the global context in an SDK addon:

```js
require('chrome').Cu.importGlobalProperties(["fetch"]);
```

I'm working on a PR that tries the SDK approach before loading any fetch libraries. (Another approach would be to have a build step that creates an SDK-compatible ping-centre.js and a web/node compatible ping-centre.js, but I noticed you've got a Makefile in this repo, and I don't totally know how I'd do that with make.) Hopefully will have the PR out within a day or so.

**Comment by emtwo** [comment]
I don't think the Makefile is necessary. I was going to add in webpack so I think that might solve this.

**Comment by 6a68** [comment]
:+1: I'm not sure how much to invest in the SDK addon special case, since those are deprecated, and WebExtensions run in a regular web page, where isomorphic-fetch should just work.

**Comment by emtwo** [comment]
Landed
https://github.com/mozilla/ping-centre/commit/1149afe5b614fb8d0abaa7b9abd7a7372438b652
