### ISSUE TITLE
Ensure ping-centre based data complies with Mozilla data retention policy

### ISSUE THREAD

**Issue by tspurway** [mozilla/ping-centre#54]
https://mana.mozilla.org/wiki/display/DATAPRACTICES/General+Data+Collection+Guidelines

In general, 180 days is the retention period, and that should be the default.

**Comment by ncloudioj** [comment]
Yep, will apply the data retention rule to all the Ping-Centre tables.

**Comment by ncloudioj** [comment]
This is already enabled in the data pipeline.
