### ISSUE TITLE
Keyword conflict in Test Pilot schema

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/ping-centre#55]
There is a field called "raw" in the Test Pilot schema, unfortunately, this is also a reserved keyword for Redshift, see details [here](http://docs.aws.amazon.com/redshift/latest/dg/r_pg_keywords.html).

@6a68 Could you consider renaming this field, please?

**Comment by ncloudioj** [comment]
Actually, there is no need to change the schema here if we change the name of this field in Redshift. In order to make it work, I'd recommend to use the "raw_ping" instead of "raw" in the Redshift table. Note that Ping-Centre will take care of the name re-mapping, no change is needed on the client side.

**Comment by 6a68** [comment]
@ncloudioj Ugh, sorry about that! Is this bug fixed, then?

**Comment by ncloudioj** [comment]
@6a68 Yes, this is fixed. Just we've renamed it as "raw_ping" in the database.
