### ISSUE TITLE
Support custom field queries for Test Pilot Snooze Tabs experiment

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/ping-centre#57]
The Snooze Tabs experiment [defines](https://github.com/bwinton/SnoozeTabs/blob/master/docs/metrics.md) its own Redshift schema with custom fields not found in the Test Pilot ping-centre schema, specifically, `snooze_time` and `snooze_time_type`.

Could a separate Redshift table be created that matches the documented schema? And, could the existing pings be inserted into that table?

I'm not yet sure if it would also be good to add the raw_ping field to the linked Redshift schema. Some queries might be more useful if they could be sorted by Firefox version. @lmorchard any thoughts? The raw_ping field contains the entire Telemetry ping, serialized as JSON.

**Comment by ncloudioj** [comment]
The ideal way to do this is introducing a new ping-centre `topic` for SnoozeTabs, which includes following steps:

* Choosing a new topic other than reusing "testpilot", e.g. "snooze_tabs" (by client)
* Defining the new schema with new fields "snooze_time" and "snooze_time_type" (by client)
* Creating a new table and ETL job to load the pings into Redshift (by ping-centre)
* Generating basic dashboards on Redash (by ping-centre)

Note:
* We have to use a new topic as its pings will be loaded into a separate table
* As @6a68 mentioned earlier, we can just reuse the "testpilot" schema for convenience
* Once the new table gets created, we can reload the previous pings to the new one
