### ISSUE TITLE
Consider shrinking the "raw" field of "TestPilot" pings

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/ping-centre#58]
We've observed that the vast majority of "raw" rows in the "testpilot" table are populated by "0" in the Redshift. The raw logs showed that most of the "raw" fileds are large JSON blobs (in 10KBs). Unfortunately, the ping-centre data processing (Disco) has a hard limit (8KBs) for the key/value size, and the system inappropriately set those overflowed fields to zero values.

This bug has made the "raw" field inaccurate, and will be fixed soon.

On the other hand, I'd recommend to consider shrinking this field for following benefits:

* To save space in Redshift, big JSON blobs will grow the database quickly 
* To improve the query performance. Despite the "raw" field isn't deemed to be frequently used, keeping it compact can result in a better query speed
* To limit the scope of data collection, there are a lot of user specif fields in the payload. Including all of them might introduce privacy concern as a result

@6a68 Shall we consider auditing this "raw" field? We'd like to hear your thoughts.

**Comment by 6a68** [comment]
@ncloudioj I think we can just do away with the 'raw' field. Most of what experiments need will be captured in their custom ping formats, and I've already extracted the most obviously helpful fields up to top level in the testpilot ping.

**Comment by ncloudioj** [comment]
@6a68 👍 Sounds good! Let's roll out the first schema migration for Test Pilot then :)
