### ISSUE TITLE
Add support for batching ping events

### ISSUE THREAD

**Issue by sleroux** [mozilla/ping-centre#61]
For activity stream on iOS, we generate a bad/undesired event whenever we encounter a highlight or top site that doesn't have an image or favicon. Currently ping centre only supports sending pings one at a time causing the panel to make potentially many network calls for each bad event it encounters. 

Can we add an API on the service side to accept an array of event data instead of a singular event?

**Comment by ncloudioj** [comment]
@sleroux Agreed, it makes no sense to make a network call for each event in your case.

Fortunately, it's not hard to add this support to ping-centre. Actually, we can still use the existing endpoint, just make a new schema for the batch mode payload as follows:

```js
{
  "topic": "activity-stream-mobile-events",  // `topic` remains at the top level
  "batch-mode": true,  // this indicates the payload is in batch mode
  "payloads": [{}, {}, {}]  // put multiple events here, Infernyx will flatten it
}
```

What do you think about the payload schema above? @sleroux

**Comment by ncloudioj** [comment]
Just be clear here, the client can still send the single event as it is. In other words, the current ping-centre endpoint will take both single mode and batch mode payloads with this change.

**Comment by sleroux** [comment]
> Actually, we can still use the existing endpoint, just make a new schema for the batch mode payload as follows

Smart. This sounds good to me!

**Comment by ncloudioj** [comment]
Okay, I'll update the documents of Ping-centre for the new schema, and will be working on the change on the server side, shouldn't take too long.

**Comment by ncloudioj** [comment]
Now deloying this feature to stage.

**Comment by ncloudioj** [comment]
It's running in Stage now. @sleroux you can play around with it now :)

**Comment by sleroux** [comment]
I've updated the iOS ping centre client to send batch events and it seems to look good from my end (status code 200) on staging. Did you want to verify from your side?

**Comment by sleroux** [comment]
Also: iOS PR for reference https://github.com/mozilla-mobile/firefox-ios/pull/2719

**Comment by ncloudioj** [comment]
Awesome! I did check yesterday, but our stage server is currently experiencing some issues, and ops folks are fixing them now. I'll verify it once it's back and let you know how it goes.

**Comment by ncloudioj** [comment]
@sleroux Yep, the batching pings are flowing to the stage, and been processed properly. I've also seen some pings with an empty `payloads` list, you might want to take a look.

```js
{"batch-mode":true,"topic":"activity-stream-mobile-events","date":"2017-05-12","payloads":[],"timestamp":1494598737926,"action":"ping_centre","ua":"Client\/3301 CFNetwork\/811.4.18 Darwin\/16.5.0"}
```

I'll deploy this change to prod soon.

**Comment by sleroux** [comment]
Thanks @ncloudioj! That looks to indeed be a bug in the iOS implementation. I'll fix it on my end.
