### ISSUE TITLE
Aboarding firefox-onboarding 

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/ping-centre#70]
The schema is still under discussion, we are likely going to have two `topics` for "firefox-onboarding", i.e. "firefox-onboarding-sessions" and "firefox-onboarding-events", respectively.

**Comment by gasolin** [comment]
related onboarding bug is filed in https://bugzilla.mozilla.org/show_bug.cgi?id=1389424

**Comment by gasolin** [comment]
I found the lib size is too large (~13xk), if we can remove `joi-browser` from the production lib(the schema should be validated during development), `sendPing` could be a lean `fetch` wrapper with a reasonable size.

**Comment by ncloudioj** [comment]
We have deployed the Ping-centre bit to prod.
