### ISSUE TITLE
Attach AWS Quicksight to the Tiles Redshift production instance

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/ping-centre#71]
Let's create an AWS Quicksight instance which is able to read from the production Tiles Redshift instance which contains all of our production Activity Stream data so that we can begin prototyping replicating all of our core telemetry visualization in Quicksight so we can evaluate how it compares to Redash.

**Comment by ncloudioj** [comment]
Just touch base with @jbuck about AWS QuickSight. So there is a security concern with the current QuickSight workflow, and the Cloud Services team is working with AWS team to solve that. They will keep us posted once we have a better understanding of it.
