### ISSUE TITLE
Track Shield experiment ID in ping payload

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/ping-centre#79]
When we build and send a ping payload, we need to include the Shield experiment IDs and branch IDs.  This will allow us to very easily isolate telemetry for a given experiment to perform meaningful analysis.  The only hiccup here is that Shield allows for multiple enrollment, so we need to figure out how to capture an array of slugs and pass that in our telemetry.

Relevant API is here:

https://dxr.mozilla.org/mozilla-central/source/toolkit/components/telemetry/TelemetryEnvironment.jsm#1002

**Comment by jaredkerim** [comment]
1) For the worst case, let's join multiple experiment ids using a separator like ',' and store them all in a string field and do substring matching

2) Let's add an optional field to the send ping method that includes an experiment slug prefix like 'activity-stream' and then filter all the experiment ids from the telemetry API to match those prefixes

**Comment by emtwo** [comment]
https://github.com/mozilla/activity-stream/issues/3350
