### ISSUE TITLE
visualize display done telemetry

### ISSUE THREAD

**Issue by emtwo** [mozilla/ping-centre#86]
Copy of https://github.com/mozilla/activity-stream/issues/2843

**Comment by emtwo** [comment]
I'll have to follow up with @dmose. I'm not sure what this one is about exactly

**Comment by dmose** [comment]
> As a developer or eng/product manager, I can see how long it takes for about:newtab to finish painting in the field so that I can both ensure that it is quick enough and notice if it regresses.

Is the user story from that bug.  @emtwo, if it's not clear enough, what information is missing?

**Comment by emtwo** [comment]
@dmose. That story is great! You also mention that the hero element captures the most important piece of this. So I wasn't sure what's missing.

So in that case, is this based on adding similar telemetry for the other components similar to what we have for the hero element?

If so, is there a separate issue to collect that data?
