### ISSUE TITLE
Activity Stream German Pocket Feed Experiment

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/ping-centre#93]
We now have an experiment live in Germany with a localized pocket feed.  We need a dashboard that compares engagement in this variant against the existing pocket engagement numbers coming from all other channels/locales.

**Comment by emtwo** [comment]
Blocked on https://bugzilla.mozilla.org/show_bug.cgi?id=1399936#c5

**Comment by emtwo** [comment]
Let's do this analysis on the pocket feed in Nightly to start.

**Comment by emtwo** [comment]
Work is being done here: https://sql.telemetry.mozilla.org/dashboard/activity-stream-system-addon-pocket_1

**Comment by emtwo** [comment]
This dashboard gives us enough information for now. closing
