### ISSUE TITLE
File redash issues

### ISSUE THREAD

**Issue by emtwo** [mozilla/ping-centre#96]
1) Permissions to make changes to dashboards (could be as simple as URL for world-writable privileges)
2) Annotations on graphs

**Comment by dmose** [comment]
https://redash.io/help/user-mgmt/user-mgmt.html#create-edit-groups suggests that some (or even most?) of the permission related stuff exists already in some form...

**Comment by emtwo** [comment]
The issues have been filed and we can follow what happens with them here:

1) https://github.com/mozilla/redash/issues/257
2) https://github.com/mozilla/redash/issues/258
