### ISSUE TITLE
Pocket Personalization in Nightly Dashboard

### ISSUE THREAD

**Issue by emtwo** [mozilla/ping-centre#97]

**Comment by jaredkerim** [comment]
This is blocked on updating Activity Stream to respond to pref changes from Shield.

**Comment by emtwo** [comment]
This is no longer blocked. The bug is fixed

**Comment by emtwo** [comment]
There were a couple of issues with the second run of this experiment too:

1) We were not targeting users with Pocket enabled by default so our population size was very small
2) The shield ID was not being captured by ping centre since it didn't contain the substring "activity-stream" so ping centre analysis was not easily possible

We're re-running this experiment here with preliminary analysis: https://sql.telemetry.mozilla.org/dashboard/activity-stream-system-addon-experiment-v2-pocket-personalization
