### ISSUE TITLE
Telemetry for bad state

### ISSUE THREAD

**Issue by piatra** [mozilla/ping-centre#98]
As an engineer, I need to monitor the performance of Activity Stream in our general population to understand performance issues and catch regressions.

https://github.com/mozilla/activity-stream/issues/2672 adds 2 new pings for `topsites` and `highlights` that are sent when render happens before data is ready. The value is the difference between data ready and first paint.

The ping documentation [is here](https://github.com/piatra/activity-stream/blob/bug-2672-telemetry-bad-state/docs/v2-system-addon/data_events.md#undesired-events-ping)

**Comment by emtwo** [comment]
@piatra I'm confused, are you asking for a review here for the issue you're working on? If not, what is this issue about?

**Comment by emtwo** [comment]
@ncloudioj can we make this issue for adding the bad state field to the database?

**Comment by ncloudioj** [comment]
@emtwo I think we already have the `assa_masga_daily` table if that's what we need for this. :)

**Comment by emtwo** [comment]
@piatra @ncloudioj ok I'm going to close this ticket then since we have this ready server-side.
