### ISSUE TITLE
Add db fields to redshift for experiment_id

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/ping-centre#99]
Ping centre will begin to collect experiment_id from Shield in its pings, we need to make sure there's also a db field for it.

**Comment by emtwo** [comment]
Nan is doing this here: https://github.com/mozilla/infernyx/pull/105

**Comment by ncloudioj** [comment]
Closed via [infernyx#105](https://github.com/mozilla/infernyx/pull/105)
